### PR TITLE
feature/velocity_controllers/joint_trajectory_controller rebased to indigo-devel

### PR DESCRIPTION
**Pull request by fmessmer**
This is a rebased version of https://github.com/ros-controls/ros_controllers/pull/109

### CODE REVIEW

**Comment by fmessmer** [comment]
Is it possible to merge this PR?
Or is there any issue left that needs to be fixed?

**Comment by adolfo-rt** [comment]
Hey there. I was on holidays, hence the response latency.

Could you please squash the four relevant commits into a single one?. After that we can merge.

**Comment by fmessmer** [comment]
I have no experience in squashing stuff. How do you normally do this? I don't want to break anything...
I guess squashing commit https://github.com/ipa-fxm/ros_controllers/commit/7d88e79907e0c59caefbfaf4ba93a481bada7ad6 will be a problem, right?

**Comment by bmagyar** [comment]
This is a nice way, by the book (have options not to squash some stuff):
http://stackoverflow.com/a/5189600

My personal preference (if you have a clean linear history to squash):
http://stackoverflow.com/a/5201642

In the optimal case squashing commits will leave you with a branch that has a single commit on top of the original repo. Squashing changes the history of the branch, so when you push it you will have to use "git push -f". Try squashing commits on a different branch first so that you won't endanger your PR contents.

**Comment by adolfo-rt** [comment]
For this particular case, this is what I recommend:
1. Remove the first commit, as it's a patch affecting hydro only.
2. Squash the last three into a single one.

In git, you can do all of this in a single interactive rebase (check out @bmagyar resources for the details of what's going on):

```
git rebase -i 7d88e79^
```

This will fire up a text editor with the four commits of this PR, starting with the oldest one.
- To get 1. done, simply remove the first line, the one containing the commit you want to get rid of. If you read the comments at the bottom, you'll see a line reading "If you remove a line here THAT COMMIT WILL BE LOST". This is what you want.
- To get 2. done, for the last two commits (ad681d0 and 9df7530) replace the initial `pick` string with `fixup` (or `f`). This will squash them into 88ea74f. Fixup is "like squash, but discards the commit's log message". This is what we want, as 88ea74f contains a sufficiently good log message.
- Save and exit. You should see a message saying

```
Successfully rebased and updated <your branch>
```
- Verify your changes. You can check the logs with `git log -n3` for example. I like to [use](http://jonas.nitro.dk/tig/) [tig](http://jonas.nitro.dk/tig/) for browsing git repos.
- Since you changed the history of the branch, you need to do a force push to propagate the changes to the remote (`-f` below):

```
git push -f <remote_name> <branch_name>
```

**Comment by fmessmer** [comment]
@bmagyar @adolfo-rt 
Thank you guys for the detailed explanations! `Squashing` - yet another git feature I am now able to use... :smile:

I cleaned up this PR so that in only consists of the relevant commit. This should be it!

**Comment by adolfo-rt** [comment]
+1

**Comment by davetcoleman** [comment]
Yay!

**Pull request merged**
