### PR TITLE
add velocity_controller/JointPositionController

### PR DESCRIPTION
**Pull request by fmessmer**
...in separate feature branch

This feature has been provided by @davetcoleman

### CODE REVIEW

**Comment by davetcoleman** [comment]
Thank you for the attribution

**Comment by adolfo-rt** [comment]
Thanks @ipa-fxm for making this a separate feature. I have looked at the code, but not ran it, so, as a last check before merging, could you or @davetcoleman confirm that you have tested it (in a robot or simulation) and that it works as expected?.

Thanks.

**Comment by adolfo-rt** [comment]
Something else. New features go to `indigo-devel`, so you should rebase your branch and open a new PR against `indigo-devel`. Expect some conflicts at the CMake level, but not much more.

**Comment by davetcoleman** [comment]
I am in Japan this summer, far away from Baxter where I developed this for. I do not use Gazebo and am unable to test this for the next month.

**Comment by fmessmer** [comment]
I haven't tested the JointPositionController's functionality yet, but I'll have a look at it...
As to rebasing and testing the feature for indigo: I'm currently still using hydro...but plan to test indigo next week...

**Comment by adolfo-rt** [comment]
@ipa-fxm you can likely build `indigo-devel` of ros_control & friends (or pretty much most of it) in an otherwise hydro environment. This package in particular should not be problematic. For testing controller behavior, it should be fine to do it on hydro. Indigo changes concern mostly the build system (drop rosbuild support) and dependency name changes (urdf-related stuff became a system dependency).

**Comment by fmessmer** [comment]
#117 rebases this feature to the latest indigo-devel branch
In case this feature does not go into hydro-devel, please close this PR!

**Comment by fmessmer** [comment]
As #117 is merged, I'll close this PR!

**Pull request closed without merging**
