### PR TITLE
Traverse URDF to base_frame to calculate wheel_separation

### PR DESCRIPTION
**Pull request by paulbovbel**
Previous behaviour was to examine only the joint connected the wheel link to its parent, which fails if wheel is not connected directly to base_link.

### CODE REVIEW

**Comment by efernandez** [comment]
@paulbovbel The euclidean distance between vectors might be modified if the left wheel to `base_link` and right wheel to `base_link` segments aren't colinear.

IMHO, for these cases it might be better to use a parameter to specify the wheel separation.
@bmagyar @artivis

**Comment by paulbovbel** [comment]
I can't think of any obvious configurations where wheels wouldn't be colinear, but it would certainly be helpful to be able to override wheel separation in general. 

This patch however would be a good start to having the controller work for URDFs where the wheels aren't attached directly to the root link. I noticed this because I'm working with the urdf tutorials (http://wiki.ros.org/urdf/Tutorials/Using%20Xacro%20to%20Clean%20Up%20a%20URDF%20File) to add a diff_drive_controller example, but the model has wheel->leg->base_link.

**Comment by bmagyar** [comment]
+1 for not using tf. 
This solution though assumes that all your frames between wheel and base share the same orientation which is not enforced anywhere. Adding up the position elements into a final vector is only valid when this orientation constraint is true.

What do you think about this?
Issue: https://github.com/ros-controls/ros_controllers/issues/167
PR: #169

**Comment by paulbovbel** [comment]
That's great, I didn't spot that thread before. For getting the wheel separation from URDF when it's not overriden via params, would you still be interested in the URDF traversal implemented in this pull? If so, I can rebase this on top of that pull once you merge it in.

EDIT: @bmagyar, I just understood what you meant about the 'same orientation', that would be an unpleasant surprise for a user. I can think about how to rework this to take any rotations in account, probably using the KDL-URDF parser.

**Comment by paulbovbel** [comment]
So, are you interested in a more 'robust' wheel_sep autodetection method rebased onto #169 ? If so, then I can investigate using KDL to get the proper wheel separation that includes any orientation changes.

**Comment by bmagyar** [comment]
Hi Paul,

Yes I do agree that removing this assumption would be beneficial, ad the KDL-URDF parser sounds good but on the other hand I'm wondering if it makes life easier for anyone apart from adding code to the controller. Personally I would prefer to keep the controller as clean as possible but I am generally open to  new features provided that there is a strong need for them and they acn be introduced in a backward-compatible way (as you see how many are coming in, and you don't see how many we have internally in PAL ;))

**Comment by paulbovbel** [comment]
@bmagyar , thanks, I'd like to come back to this. Meanwhile, could you please release a new version of ros_controllers, so that #169 is included?

**Comment by adolfo-rt** [comment]
> @bmagyar , thanks, I'd like to come back to this. Meanwhile, could you please release a new version of ros_controllers, so that #169 is included?

https://github.com/ros/rosdistro/pull/8324

**Comment by bmagyar** [comment]
Thanks Adolfo!

**Pull request closed without merging**
