### PR TITLE
[DiffDrive] dynamic reconfigure

### PR DESCRIPTION
**Pull request by artivis**
Add a dynamic_reconfigure server to diff-drive controller allowing to change some parameters on the fly, e.g. left/right wheel multiplier, enable_tf etc...

### CODE REVIEW

**Comment by artivis** [comment]
@bmagyar Hola.
@efernandez you advised me to try a dyn-reconf scheme in #293, here it is.
I have no idea how to test that the multipliers have been changed given the current state of `diffbot`. Any suggestion ??

**Comment by bmagyar** [comment]
Test: you could try to change the wheel multipliers in an extreme way and use some pre-compute your expected end state with correct ones and multipliers that are __very off__.

**Comment by artivis** [comment]
The problem is that the per-wheel cmd are computed from the corrected wheel radii (multiplier * wheel_rad), thus whether you integrate with mutipliers set to 0.5 or 1.5 your integration should end-up roughly the same.

**Comment by bmagyar** [comment]
That statement begs this reply: if we cannot measure the difference of setting different params, what's the point of the whole thing?

**Comment by artivis** [comment]
We cannot measure any diff with the current test because the `diffbot` is too simplistic - [see here](https://github.com/ros-controls/ros_controllers/blob/kinetic-devel/diff_drive_controller/test/diffbot.h#L104).  
If we had an actual simulator (say Gazebo) then a difference would appear.  
I guess the `diffbot` could be updated to take into account the kinematic defined in the robot_model and compute the joint positions from it.

**Comment by artivis** [comment]
Unwip since #314 was merged.

**Comment by artivis** [comment]
`joint_trajectory_controller` tests are failing.

**Comment by artivis** [comment]
Hi @efernandez, with #314 merged I'm looking forward to your review :D

**Comment by bmagyar** [comment]
Please resolve the current conflicts. 

Also ping @efernandez for review

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
