### PR TITLE
Add tests for velocity_controllers::JointTrajectoryController

### PR DESCRIPTION
**Pull request by miguelprada**
This PR adds a VelocityJointInterface to [`RRBot`](https://github.com/miguelprada/ros_controllers/blob/velocity_iface_tests/joint_trajectory_controller/test/rrbot.cpp), and duplicates the [tests](https://github.com/miguelprada/ros_controllers/blob/velocity_iface_tests/joint_trajectory_controller/test/joint_trajectory_controller_vel_test.cpp) being run for the position-based joint trajectory controller.

### CODE REVIEW

**Comment by bmagyar** [comment]
ok Miguel, one last thing: could you please [squash](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes) your commits on this PR?

**Comment by miguelprada** [comment]
Done. I also rebased on top of the current `kinetic-devel` while I was on it, since the only commit that was there was something on the travis configuration. Hope this is fine.

**Comment by miguelprada** [comment]
After squashing and rebasing I found a compilation error which made the CI job fail. It had to do with the API change introduced in ros-controls/ros_control@afaf940, and I'm not quite sure how it flew under my radar (probably some messed up workspace with `indigo-devel` branch of `ros_control`).

Anyways, after fixing it, the travis job still fails, only this time on some `diff_drive_controller` test. Don't think there's anything I should do about this, right?

**Comment by bmagyar** [comment]
Thanks for sticking around with this one, merging...

**Pull request merged**
