### PR TITLE
Allow travis to run tests, code modified from kinetic

### PR DESCRIPTION
**Pull request by graiola**

### CODE REVIEW

**Comment by bmagyar** [comment]
https://travis-ci.org/ros-controls/ros_controllers/jobs/226834477#L916

This only seems to fail on the test we disabled in Kinetic!

**Comment by graiola** [comment]
It seems we have a winner :1st_place_medal:

**Comment by bmagyar** [comment]
I put #270 in to fix this. Let's see about it after that.

**Review by bmagyar — CHANGES_REQUESTED** [review]
Please change the `recipients` field to our email addresses. 
Enrique & me for sure, put yourself as you prefer.

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
