### PR TITLE
feature/velocity_controllers/joint_position_controller rebased to indigo-devel

### PR DESCRIPTION
**Pull request by fmessmer**
This is a rebase of https://github.com/ros-controls/ros_controllers/pull/108

### CODE REVIEW

**Comment by fmessmer** [comment]
Is it possible to merge this PR?
Or is there any issue left that needs to be fixed?

**Comment by adolfo-rt** [comment]
Coming back to the open question from #108 ([here](https://github.com/ros-controls/ros_controllers/pull/108#issuecomment-50589045)). What kind of testing or validation has this controller seen?. Given that there is no test suite, I'd at least like confirmation that under some conditions the controller behaves as expected.

**Comment by fmessmer** [comment]
We have been usíng this together with simulation (Gazebo) and a (very simple 1DoF) hardware.
The controller appears to do what it is promising: position control for velocity interfaces...

**Comment by adolfo-rt** [comment]
Thanks for the confirmation.

Please remove the first commit, as it's a patch that affects hydro only, and is orthogonal to this PR.

**Comment by fmessmer** [comment]
I cleaned up this PR so that in only consists of the relevant commit. This should be it!

**Comment by adolfo-rt** [comment]
+1

**Pull request merged**
