### PR TITLE
JointPositionController can now load the robot_description from root_node_handle ns

### PR DESCRIPTION
**Pull request by shisha101**
Please refer to Issue https://github.com/ros-controls/ros_controllers/issues/256

### CODE REVIEW

**Comment by graiola** [comment]
Hello,
I think this could be a possible solution to issue #244 but as it's implemented it would break the interface.
A fix would be to use an overloaded method or a method with default argument.

@bmagyar what do you think?

**Comment by bmagyar** [comment]
Good point. I think we have to also organise the effort of supporting non-global `robot_description` parameters in all of `ros_controllers` including a list of todos, extra tests to keep this feature in place and guidelines for people implementing new controllers to make sure they have this feature too.

**Comment by bmagyar** [comment]
@shisha101 please make sure that your changes are API and ABI compatible with the current version as we cannot break these in Indigo.

**Comment by shisha101** [comment]
Will do. I'll post back when it's ready.

**Comment by bmagyar** [comment]
Hello,

I believe we should push this support through the same way (&same code) as it was done on #245. We https://github.com/ros/robot_model/pull/193 will allow for that.

As such I'm closing this PR.

**Comment by shisha101** [comment]
Looks good, thanks for the heads up :)

**Comment by emekBaris** [comment]
@bmagyar, this feature is missing in melodic-devel.

**Pull request closed without merging**
