### PR TITLE
joint_position_controller.cpp bug

### PR DESCRIPTION
**Pull request by mahisorn**
I tested joint_position_controller in effort_controllers with gazebo and found that error for revolute joint has incorrect sign. I fixed the problem as show in the diff.

Hope this help.

### CODE REVIEW

**Comment by mahisorn** [comment]
Just found that It was fixed in hydro-devel branch and it was argument order errors.

**Comment by davetcoleman** [comment]
Was this fixed in master?

**Comment by mahisorn** [comment]
Not yet. Do I need to create a new pull request ?

I just update and merge with the upstream.
https://github.com/hiveground-ros-package/ros_controllers/compare/ros-controls:master...master

**Comment by davetcoleman** [comment]
No, I was asking if @jbohren's fix had been merged into master, which is a duplicate of yours (I believe he committed his first)

**Comment by davetcoleman** [comment]
The above pull request should fix this issue, since the needed fix was already added to hydro-devel.

Feel free to re-open this issue if it does not fix the problem, thanks!

**Pull request closed without merging**
