### PR TITLE
joint_trajectory_controller rqt plugin

### PR DESCRIPTION
**Pull request by adolfo-rt**
Not ready for merge yet, depends on ros-controls/ros_control#165.

The code has quite a few inline TODOs, but the GUI is pretty solid.

Initial plugin features:
- Allows to select any _running_ joint trajectory controller from any
  controller manager.
- Two modes:
  - **Monitor** Joint display shows actual positions of controller joints
  - **Control** Joint display sends controller commands
- Max joint speed is read from the URDF, but can be scaled down for safety.

Snapshot of the standalone plugin, as rendered by KDE:
rqt_jtc

Snapshot of an rqt perspective combining two instances of the plugin with `rqt_plot` and `rviz`. I think this is really cool:

rqt_perspective

### CODE REVIEW

**Comment by adolfo-rt** [comment]
Note to self: Some custom URDF parsing code could get removed once ros/urdfdom#36 gets fixed.

**Comment by sachinchitta** [comment]
Looks really nice (and very useful during debugging).

**Comment by davetcoleman** [comment]
Awesome!

**Comment by adolfo-rt** [comment]
Squashing commits for merge.

**Comment by jbohren** [comment]
I missed this at some point, but it looks cool. I'm going to try this out with Conman and my RML-based controller. Now if only someone would make rqt_plot better.

**Comment by adolfo-rt** [comment]
> I missed this at some point, but it looks cool. I'm going to try this out with Conman and my RML-based controller.

Let me know how it goes...

> Now if only someone would make rqt_plot better.

Yeah, I hear you. I hoped to spend some cycles on `rqt_plot` before the summer break, but that didn't happen :'-(

**Pull request merged**
