### PR TITLE
increasing seq in differential_drive controller topic headers

### PR DESCRIPTION
**Pull request by Timple**
This pull request solves https://github.com/ros-controls/ros_controllers/issues/251

However, it was not the source of the problems we where having. Feel free to accept or reject based on your judgement.

### CODE REVIEW

**Comment by bmagyar** [comment]
Could I ask you to squash those commits? I'd merge it then

**Comment by Timple** [comment]
Done!

**Comment by bmagyar** [comment]
Ok, I only see `seq_ += seq_;` or similar. This'd double the value of the sequ variable, which is probably not the intended behaviour but since it starts off with 0 as initial value it stays there, doesn't it?

**Comment by Timple** [comment]
That is absolutely right. It slipped through when I was trying to clean up stuff.

**Comment by bmagyar** [comment]
+1 on first look, I'll try to test it tonight

**Comment by bmagyar** [comment]
I'm now a bit puzzled whether we should actually go this way.
Give this a read:
https://discourse.ros.org/t/is-the-sequence-number-in-header-message-deprecated/1528

What is your opinion? I'd prefer not to add changes for this then.

**Comment by mathias-luedtke** [comment]
>  I'd prefer not to add changes for this then.

+1

**Pull request closed without merging**
