### PR TITLE
Increase jtc. test time limit to 120s

### PR DESCRIPTION
**Pull request by efernandez**
This cherry-picks https://github.com/ros-controls/ros_controllers/pull/222 into `kinetic-devel`.

@bmagyar for review

### CODE REVIEW

**Comment by bmagyar** [comment]
Yeah you should cherry pick a lot more than that ;)

Kinetic is still running the tests against hydro...

**Comment by efernandez** [comment]
:facepunch: Oops! Ok, I'll create the PR for the tests (and proper compilation target) first and once it gets merge we can re-run the job of this one.

Thanks!

**Comment by bmagyar** [comment]
Bump

**Comment by bmagyar** [comment]
I guess I can merge this one now, right @efernandez ?

**Comment by bmagyar** [comment]
Btw aren't this out of interest now? It seems all our tests are ok. Please close in this case.

**Comment by efernandez** [comment]
Closing as (according to @bmagyar ) tests are already passing.

This PR only increases the time-out of one rostest, so there's no need for that if it's already passing.

**Pull request closed without merging**
