### PR TITLE
Switch the read and write bodies. 

### PR DESCRIPTION
**Pull request by wilcobonestroo**
The code was confusing with respect to the ros_control documentation. Now it is in line with that documentation.

### CODE REVIEW

**Review by mathias-luedtke — CHANGES_REQUESTED** [review]
The current code is correct (the data gets updated by `write`).
The patch introduces writing in `read`, which is not intended.

I am not sure why the `read` function is printing the previous command..
Moving this into `write` might be an option, but for now I would not change it.

> Now it is in line with that documentation.

Which documentation are you referring to?

**Comment by wilcobonestroo** [comment]
In the code, `pos_` and `vel_` refer to the states of the joint and `cmd_` refers to the command that is send to the joints. In the current code, the `pos_` and `vel_` are filled in the `write` and `cmd_` is read in the `read` function.

**Comment by mathias-luedtke** [comment]
`write` applies the `cmd_` to the new state in `pos_`/`vel_`. It emulates one control step without any delay.
[rrbot](https://github.com/ros-controls/ros_controllers/blob/melodic-devel/joint_trajectory_controller/test/rrbot.cpp) is doing the same.
It is just a test mock-up anyway, I don't see the need to change it.

> cmd_ is read in the read function.

`cmd_` just gets printed, `read` is a NOP.

**Comment by wilcobonestroo** [comment]
Ah. Now I see. I was thinking about a real robot and not about emulation. Thank you for your answer.

**Pull request closed without merging**
