### PR TITLE
Xacro dependency does not work correctly in Groovy

### PR DESCRIPTION
**Pull request by davetcoleman**
I've had to make this fix in several places this past summer, but even after talking with the ROS infrastructure team I'm not sure what causes it.

### CODE REVIEW

**Comment by adolfo-rt** [comment]
Xacro has not been catkinized in Groovy. That's why it fails. IIRC, when I remove the catkin dependencies rosdep complains. I'd rather not apply this change in the Hydro branch, as it works as expected. How about backporting the controller to Groovy and applying the change there?.

**Comment by davetcoleman** [comment]
I think if we backport it to Groovy we will also have to backport ros_controls and fix other stuff - a whole can of worms.

In other packages in ros_control and ros_controllers I've run into this same xacro issue when installing on Groovy, and so the fix has been to just remove it. I think you'll find the xacro dependency missing from a lot of things because it is missing in Catkin. rosdep does not complain - i have already tested this.

@dirk-thomas there is no better fix for now, correct?

**Comment by dirk-thomas** [comment]
I don't know enough about the issues you describe.

If a package is not catkinized you can not depend on it from within a catkin package. If xacro was catkinized for hydro it makes sense to keep the dependency on it in the hydro branch if your package uses it.

**Comment by davetcoleman** [comment]
Hmmm, well I guess the other option is as Adolfo suggested of completely back porting the ros_control and ros_controllers branches of Hydro back into Groovy. I guess no one is really using those branches except maybe Hidof (@wmeeusse), but currently the Groovy branch is 9 months behind and "0 commits ahead and 207 commits behind hydro-devel"

It is probably easier to just delete xacro as I've done everyone else for Hydro.

I'm just trying to support Rethink @rethink-cgindel

**Comment by adolfo-rt** [comment]
> It is probably easier to just delete xacro as I've done everyone else for Hydro.

Groovy should not stand in the way of Hydro. That's the reason we have distro-specific branches.

If back porting to Groovy is as simple as merging hydro-devel into groovy-devel, and deleting the xacro dependency in the `CMakeLists.txt`, that doesn't sound like a whole can of worms, and what's best, you've already verified that it works.

**Comment by davetcoleman** [comment]
I have emailed Wim to see if this would be ok.

**Comment by davetcoleman** [comment]
Wim's response:

> It's been awesome to follow the development in the ros_control world!
> It's always okay to get bug fixes backported into an older release, as
> long as we're not modifying any of the existing API's. We do have
> customers using ros_control, so the API stability is a wonderful
> feature.  Does any of the 207 commits in the hydro branch break the
> groovy API's?  It's of course also possible to just backport the most
> needed bugfixes.

**Comment by adolfo-rt** [comment]
We should compare the two branches, but most things have been just API additions: new interfaces or new controllers. Still, it's best to check. A diff on the headers should do.

**Comment by davetcoleman** [comment]
I think there's a lot of headers to worry about. I might just create a `groovy-hydro-devel` branch that is the backported hydro, and clarify this on the README.

**Comment by adolfo-rt** [comment]
`groovy-backport`?. So if we go that path, we can safely cancel and close this PR, right?.

**Comment by davetcoleman** [comment]
I have created the branch and updated the Gazebo documentation.
https://github.com/ros-controls/ros_controllers/tree/groovy-backported-hydro

**Pull request closed without merging**
