### PR TITLE
Set desired in starting

### PR DESCRIPTION
**Pull request by sachinchitta**
I think desired state should be updated in starting to match the current state. (Also current state should first be initialized here since the joints are going to be read anyway in the first setHold()).

### CODE REVIEW

**Comment by adolfo-rt** [comment]
I'd like to understand what the problem is, and I can't figure it out only by looking at the proposed solution. Could you please elaborate on this?.

I have two questions on the patch:
1. Why does `current_state_` need to be refreshed on `starting()`?. I don't see any harm in doing it, but I also don't see why it's necessary. The variable is not used in `starting()`, but in `update()`, where it currently gets refreshed.
2. Why do you need to set `desired_state_ = current_state_`. This is supposed to be done in `setHoldPosition(time_data.uptime)`, which takes place just after your patch.

Maybe there's something amiss on how `setHoldPosition()` is implemented, which is causing you trouble.

**Comment by dcconner** [comment]
Our approach, related to #144 and #177, was to have the joints desired pose stored in HWInterface, and upon switching controllers set the desired to that prior desired value, and initialize integral terms in PID to give bumpless control.  Jumping to current  actual position for the desired on startup may not give you the desired behavior, but the actual behavior will be somewhat application specific.  Again, I don't think there is a single best solution, so having some easy way to change implementations of this low level behavior might be in order long term.

We just did our own thing in a custom fork, and didn't intend to change the standard behavior.

**Comment by fmessmer** [comment]
I think I proposed something similar in #170!
The JointPositionInterface, definitely does not start in "semantic zero".

**Comment by jschleicher** [comment]
Can be closed here.

The diff was part of the discussion in #297 and was merged there.

**Pull request closed without merging**
