### PR TITLE
Added more debug and error information

### PR DESCRIPTION
**Pull request by davetcoleman**
Needed while I was debugging and setting up the trajectory controller.

### CODE REVIEW

**Comment by adolfo-rt** [comment]
The ROS logger is not realtime-safe. All the proposed log statements except the [last one](https://github.com/ros-controls/ros_controllers/pull/47/files#L0R504) take place in the realtime loop, so I can't merge them. Writing realtime code is like walking on eggshells ;-)

**Comment by davetcoleman** [comment]
Ah, that's true. 

But these error/debug messages are pretty useful and necessary for figuring out the state of the trajectory controller - its good software practice to have user friendly feedback. There needs to be some way to provide similar functionality. Also, it does seem to me that, though in the realtime loop, these messages will be output very rarely so won't _really_ affect much, right?

Or, should we perhaps make some sore of [realtime_tools](https://github.com/ros-controls/realtime_tools/tree/hydro-devel/include/realtime_tools) roslogger?

**Comment by jbohren** [comment]
> Or, should we perhaps make some sore of realtime_tools roslogger?

This is easier said than done. For example, std::stringstream isn't real-time safe.

**Comment by davetcoleman** [comment]
What if we add an option in the controller configuration yaml named something like "nonrealtime_debug_ouput: true" and have some of my suggested user feedback info be used if that setting is used? it would of course default to false.

**Comment by adolfo-rt** [comment]
For the specific problem of the reason why the goal was aborted, the action goal result reports this information in the form of an [error code](https://github.com/ros-controls/control_msgs/blob/master/control_msgs/action/FollowJointTrajectory.action#L29), which can be printed out by the clients in non-realtime. I recognize that it would be best to print it from the controller so the logging code lives in a single place.

More generally speaking, there's a compromise to live with here. The ros_control project so far does not contain RTOS-specific intrinsics, and strives to allow the same binary to work both on realtime and non-realtime deployments. Also, ros_control is rather light on dependencies.

OTOH, projects like Orocos generate separate binaries for different RTOS targets, and use RTOS-specific intrinsics. Orocos has good working solutions for most RT-related problems one might encounter like concurrencly handling, clock access and logging. Yes, there is a log4cxx (cousin of log4cpp) based reatime logger.

A good discussion would be to determine the extent to which it makes sense to put effort to Orocos and ros_control so they can work together. Being a 5-year Orocos user, I sometimes feel frustration of not being able to do in ros_control things I already took for granted in Orocos. YMMV.

On these lines @jbohren has been very quietly (but effectively) working on adding native support to ROS services and actions to Orocos, but he seems to not want to talk much about it ;-)

**Comment by adolfo-rt** [comment]
> What if we add an option in the controller configuration yaml named something like "nonrealtime_debug_ouput: true" and have some of my suggested user feedback info be used if that setting is used? it would of course default to false.

Not my favorite option.

**Comment by davetcoleman** [comment]
The FollowJointTrajectory error codes are nice, but I've been needing more info than just that, such as which joint caused the error, what the position/tolerance/values were, etc. 

I've also been impressed with @jbohren's work with getting Orocos back up to par with the latest changes in ROS. I know Orocos is a very powerful set of libraries and I'm surprised to hear you have experience with it but don't still use it. I'm curious - why bother with ros_control at all? I only don't use it because its far more complicated and seems to have a much bigger learning curve than ros_control has had.

**Comment by adolfo-rt** [comment]
> The FollowJointTrajectory error codes are nice, but I've been needing more info than just that, such as which joint caused the error, what the position/tolerance/values were, etc. 

Very good point!. Noted.

> I'm curious - why bother with ros_control at all? 

Good ROS and Gazebo integration, there was already a good starting point, and ros_control is likely to reach critical mass. I'm still using Orocos, and I wrap my hardware abstraction inside it. With ros_control is in shape, we can start thinking of the next steps, and how to make it better (maybe by leveraging Orocos under the hood).

**Pull request merged**
