### PR TITLE
Added clamping to URDF effort and velocity limits.

### PR DESCRIPTION
**Pull request by jim-rothrock**
The effort and velocity values in the effort-based joint position and velocity controllers now obey the effort and velocity limits specified in URDF files.

Without these changes, using a JointVelocityController with an apparently small derivative gain, such as 0.01, resulted in large effort values being sent to Gazebo. If Gazebo 1.9.1 received such a large effort value, it moved many of the model's links to the world's origin, making the model unusable. As long as reasonable effort limits are specified in the URDF file, the changes I have made to the position and velocity controllers prevent PID gains from resulting in an unusable Gazebo model.

### CODE REVIEW

**Comment by adolfo-rt** [comment]
Hey Jim,

Thanks for your effort. Before accepting this PR, I'd like you to consider what I believe is a better alternative. ros_control has the [joint_limits_interface](https://github.com/ros-controls/ros_control/tree/hydro-devel/joint_limits_interface) package specifically aimed at enforcing joint limits for different hardware interfaces. The upside of using this package is that joint limits are enforced in a single place inside your robot hardware abstraction, and not in the controllers. This is good because:
- The choice of a joint limits enforcing policy affects only your robot, whereas if you hardcode it in a controller, you're imposing it on all users of that controller.
- It allows you to test the same controller with different joint limit enforcing policies (or none).
- The already implemented joint limit enforcing policies are better than just a saturation.

My recommendation is then to give this package a try, start by the [README.md](https://github.com/ros-controls/ros_control/blob/hydro-devel/joint_limits_interface/README.md), and add a joint limits interface it to your hardware abstraction (eg. to [gazebo_ros_control](https://github.com/ros-simulation/gazebo_ros_pkgs/tree/hydro-devel/gazebo_ros_control)).

Let me know what you think.

**Comment by jim-rothrock** [comment]
I'll take a look at addiing a joint limits interface to gazebo_ros_control.

**Comment by adolfo-rt** [comment]
Great!. Plase come back if any questions or issues arise, or if you see parts of the documentation lacking clarity.

**Comment by davetcoleman** [comment]
Jim, this is a good feature that I overlooked in the gazebo_ros_control plugin. But Adolfo is right, the better place for it would be with the joint_limits_interface implemented within the default_hardware_interface of the Gazebo package. Let me know if you get stuck on that, thanks!

**Comment by jim-rothrock** [comment]
I'm now using joint_limits_interface to enforce joint limits in gazebo_ros_control, so I've closed this pull request.

**Comment by davetcoleman** [comment]
great work!

**Pull request closed without merging**
