### PR TITLE
Allow diff_drive_controller to use spheres as well as cylinders

### PR DESCRIPTION
**Pull request by mallanmba**
Allow diff_drive_controller to use spheres as well as cylinders for wheel collision geometry. Cylinders are not well behaved on Gazebo/ODE heightfields, using spheres works around the issue.

### CODE REVIEW

**Comment by bmagyar** [comment]
Upon a quick glimpse, it looks quite ok and I see the point in doing this. 

Allow me to ask you for a set of tests (add it to this PR) that exercises this feature. Look in our test suite for tests related to the cylinder-feature, you can find everything in the `test` folder.

**Comment by bmagyar** [comment]
:+1: 
I've looked at the proposed changes and you have my thumbs up, but I overlooked the branch you were proposing the changes to. 

As Indigo is now considered stable we are only pushing bugfixes there, all new features should go to ROS Kinetic. Please rebase or cherry-pick and open a pull request against kinetic-devel.

**Comment by bmagyar** [comment]
Bump.

@mallanmba could you please rebase this PR on kinetic-devel? I'd merge it right after that.

**Comment by mallanmba** [comment]
Sorry, sure - I'll try to get back to this soon - I'm developing on indigo
still and don't have an active kinetic development environment yet. Will
try to get to it this week.
-Mark

**Pull request closed without merging**
