### PR TITLE
Added param to remap joint_states topic

### PR DESCRIPTION
**Pull request by hvpandya**
Optional parameter to remap the joint_states topic.

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
This is a variation of #310.
I am sorry, bu I still see no point in adding this functionality.
Why do you need this?

**Comment by hvpandya** [comment]
There are situations in which one might want multiple joint_state topics (desired vs current) concurrently and adding the ability to rename the joint_states topic to something more meaningful in a given context would be great.

For instance renaming it to something like current_state or current/joint_state or desired_state and so on.

**Comment by mathias-luedtke** [comment]
> There are situations in which one might want multiple joint_state topics (desired vs current) concurrently and adding the ability to rename the joint_states topic to something more meaningful in a given context would be great.

This is not the purpose of `joint_state_controller`.

**Comment by hvpandya** [comment]
I did not mean multiple instances of joint_state_controllers, I meant multiple topics with the joint_state msg type. 

The fact that it cannot be renamed to even 'joint_state' instead of 'joint_states' is a bit weird. Feel free to close the PR if you still disagree.

**Comment by mathias-luedtke** [comment]
> The fact that it cannot be renamed to even 'joint_state' instead of 'joint_states' is a bit weird.

You can remap the name quite easily.
Or you could run the driver in its own namespace.

**Pull request closed without merging**
