### PR TITLE
Clean CMakeLists.txt and package.xml files of diff_drive_controller package

### PR DESCRIPTION
**Pull request by mateus-amarante**
Apply updates suggested in #513:

Clean dependencies (find missing/unnecessary dependencies)
Apply consistent format to package.xml and CMakeListst.txt
Fix major inconsistencies detected by catkin_lint (e.g. double find_package)

### CODE REVIEW

**Comment by bmagyar** [comment]
Looks good to me! I've rebased it to have the benefits of the new CI updates

**Comment by bmagyar** [comment]
boost details seem to be an overkill

**Comment by mateus-amarante** [comment]
> boost details seem to be an overkill

Actually, there was a mistake there. All the header-only modules of Boost are gathered in the `headers` component. The last update fix it. If you still think it is an overkill, I can remove the dependency.

**Review by bmagyar — APPROVED** [review]
Having the boost stuff fully declared is nice, it should keep the package more future-proof, it's just not what I'm used to ;) 

Cheers for this, merging...

**Pull request merged**
