### PR TITLE
jtc: Enable sending trajectories with a partial set of joints

### PR DESCRIPTION
**Pull request by beatrizleon**
Fixes https://github.com/ros-controls/ros_controllers/issues/182.

This is the same pr as https://github.com/ros-controls/ros_controllers/pull/185 but we rebased it to Kinetic. I have tested it on a docker image and all test are passing. Also commits are compresed just to one.

@bmagyar let us know if this is ok

### CODE REVIEW

**Comment by bmagyar** [comment]
Hi, thanks for rebasing! Since this is quite a major addition I'd prefer to see Travis being all green about it. 

As far as I understood @efernandez should have the Travis builds fixed very soon.

**Comment by efernandez** [comment]
@bmagyar which tests are failing? My connection is a little slow ATM.

If it's the jerk test on the diff drive controller, I recommend kicking the test job again or just merge. I'm going to create a PR to disable them for now.

**Comment by efernandez** [comment]
Finally could see the job output. It seems that something does NOT compile:

``` bash
/home/travis/ros/ws_ros_controls/src/ros_controllers/velocity_controllers/src/joint_position_controller.cpp:241:41: error: ‘struct control_msgs::JointControllerState_<std::allocator<void> >’ has no member named ‘antiwindup’
```

Maybe this needs to be rebased on top of `kinetic-devel`?
I have to confirm the test job is actually running against kinetic, since we had some issues related with that, but I think they got solved with the Travis support that finally got merged.

**Comment by beatrizleon** [comment]
I have merged the latest changes on kinetic-devel but travis is still failing. As far as I can tell is a test failure in diff_drive_controller.
screenshot from 2016-09-12 11 35 29

**Comment by bmagyar** [comment]
Hi @beatrizleon,
Sorry for the long delay. I'd be up for merging if you could rebase the PR again. 
(Something like `git pull --rebase upstream` should do the trick, please try to avoid merging back onto it).

**Comment by beatrizleon** [comment]
@bmagyar I did the rebase but test is still failing `diff_drive_controller/test_results/diff_drive_controller/rosunit-diff_drive_limits_test.xml: 6 tests, 0 errors, 1 failures`

**Comment by bmagyar** [comment]
Don't worry about that @beatrizleon , that test has been haunting us for a while now...we cannot get it to run properly on travis, everywhere else it runs fine.

Upon quadruple-checking the code, I've spotted that the new test file `joint_trajectory_controller/test/joint_partial_trajectory_controller_test.cpp` has Adolfo as author and a PAL license. You may want to change that to yourself and naming Shadow Robot in the text.

Other than that if you are ok I could merge

:+1:

**Comment by beatrizleon** [comment]
@bmagyar thanks for spotting that! I updated the copyright info. Let me know if it is ok. I am looking forward to the merge :)

**Comment by bmagyar** [comment]
This took quite a while. Thank you for sticking around and making sure it makes it to the merge!

**Comment by beatrizleon** [comment]
Thank you!

**Pull request merged**
