### PR TITLE
Sync hydro-devel

### PR DESCRIPTION
**Pull request by efernandez**
This PR has all the commits that have diverged on [PAL Robotics' fork in the hydro-devel branch](https://github.com/pal-robotics-forks/ros_controllers/tree/hydro-devel) and [ROS controls' repository in the indigo-devel branch](https://github.com/ros-controls/ros_controllers/tree/indigo-devel).

Several conflicts during the merged were solved, and all tests pass after the merge in my [fork](https://github.com/efernandez/ros_controllers/tree/hydro-devel).

The commits that diverged affect mainly the diff_drive_controller. If required, I can remove from here other commits like the ones for rqt plugin developed for the joint_trajectory_controller. Anyway, everything builds and the tests pass.

After this PR I can prepare another one for indigo-devel in ros-controls.

### CODE REVIEW

**Comment by bmagyar** [comment]
Big thanks for this!
LGTM but @adolfo-rt may have some comments on non-diff-drive related changes.

**Comment by efernandez** [comment]
@adolfo-rt any concern about the non-diff-drive related changes? You can think of this PR as merging PAL Robotics' hydro-devel upstream. From indigo-devel I simply cherry-picked the diff_drive_controller changes (mainly one of the latest PRs).

**Comment by efernandez** [comment]
@adolfo-rt Any update on this? Have can I help to make this merged?

IMHO this is a special case of PR, everything are commits already reviewed on other PRs, and all the tests pass. If I did the merge (resolving the conflicts) properly, everything should be fine.

**Comment by adolfo-rt** [comment]
Hi @efernandez, I'll review this PR and other pending issues from June 15 onwards. Before that date, all bets are off. Thanks for your understanding.

**Comment by efernandez** [comment]
Just a gently reminder.

Let me know if something went wrong with my manual merge from the different forks.

**Comment by adolfo-rt** [comment]
I finally had some time to review the PR. Thanks for your patience.

This PR seems to do multiple things: Sync PAL Robotics' `hydro-devel` fork, which have not yet been merged upstream, and backport changes from `indigo-devel`. The changes affect multiple packages. I propose a separation of this PR into more than one:
- The default development branch is `indigo-devel`, so the changes from PAL Robotics' fork should be rebased against this repo's `indigo-devel`, not `hydro-devel`. I would highly recommend some rebasing to have a more succinct history, which currently is a bit messy, and contains multiple commits with duplicate summaries (confusing).
- Once a PR with (hopefully) few commits has been merged into `indigo-devel`, you can propose a backport to `hydro-devel`, and/or a forward port to `jade-devel` in additional PRs. Having a succinct history is especially convenient when back- and forward-porting changes.
- **Very important** Hydro was officially EOL'ed in [April 2015](http://wiki.ros.org/Distributions/Timeline). As such, I'm inclined to only take bugfixes, and no new features into `hydro-devel`.

**Comment by efernandez** [comment]
@adolfo-rt My intention was to move this into indigo-devel, so I'll try to prepare a PR against it directly.
Unfortunately, it'll take me some time. As I mentioned before, the different forks and branches have diverged too much.

I also have to look for some time to work on this, at this moment I can't.

Regarding the number of commits, at most I see one that get duplicated in the manual merge, but the rest are all commits from PAL's fork. Do you want me to squash those commits? I think it's better to preserve the history from there.

**Comment by adolfo-rt** [comment]
> Regarding the number of commits, at most I see one that get duplicated in the manual merge, 

I counted at least four duplicate commit summaries:

```
Add tests for preserve turning radius
Limit jerk
Add jerk limits tests
Add default-true parameter "~enable_odom_tf"
```

> but the rest are all commits from PAL's fork. Do you want me to squash those commits? 

Yes, but not into a single commit. If possible, squash groups of similar commits into a single changeset (e.g., feature + test + doc). Also, ideas that didn't pan out could be left out altogether. I'm thinking of `Add preserve_turning_radius param` e0766ba, which got undone in `Revert "Preserve radius"` b6d375b.

You're the author of most of those commits, so nobody better than you to identify the changesets that can be squashed.

> I think it's better to preserve the history from there.

I don't. The history of PAL's repo reflects the development process, which naturally goes back and forth. It is highly desirable that upstream has an easy to read history.

**Comment by efernandez** [comment]
@adolfo-rt #183 replaces #180 following your comments.

Closing #180 ...

BTW, note that at the end I've found that most of the commits were already merged.

**Pull request closed without merging**
