### PR TITLE
[diff_drive_controller] swap implementation of read and write methods of Diffbot class

### PR DESCRIPTION
**Pull request by fjp**
This PR was discussed with @matthew-reynolds in #462 and swaps the implementations of the `read()` and `write()` methods of the `Diffbot` class in the `diff_drive_controller` package.

I've run all the tests for `diff_drive_controller` successfully. 

If this is PR gets accepted I can start looking at the other mentioned tests in #462.

### CODE REVIEW

**Review by matthew-reynolds — APPROVED** [review]
Personally this looks good to me, but looking at @ipa-mdl's review of #364, I think this has a better chance of more wide-spread approval if we focus on only moving the command print, and leaving the calculations where they were.

Ping @bmagyar @ipa-mdl for your thoughts. Full discussion in #462

**Comment by bmagyar** [comment]
Thanks guys for the discussions. I think it is easy to swap read/write as it largely depends on one's directional perspective, probably this is what happened when we first wrote those tests.

I was tempted to accept this right away *but* the little engineer on my shoulder says: "If you are unhappy with unclear documentation and want to fix code, please also take time to update said documentation.". In this case it'd mean updating the docstrings for `RobotHW::read()` and `RobotHW::write()`

**Comment by fjp** [comment]
Thanks @matthew-reynolds and @bmagyar looking into this PR. 

I think with this PR the current docstrings of [`RobotHW::read`](https://github.com/ros-controls/ros_control/blob/b78bccb5f3768d1726db79acbe8837cc5187b515/hardware_interface/include/hardware_interface/robot_hw.h#L164) and [`RobotHW::write()`](https://github.com/ros-controls/ros_control/blob/b78bccb5f3768d1726db79acbe8837cc5187b515/hardware_interface/include/hardware_interface/robot_hw.h#L172) describe the correct behaviour and don't necessarily need to be changed. 

To summarise why I created #462 : I first read the documentation (of the hardware_interface), then looked at the tests of `DiffBot` and was confused with the implementation of `DiffBot`'s `read()` and `write()` methods because it didn't fit to the documentation. Now with this PR, I think doc and code fit together.

However, I guess it could help to put some more details into the docstrings regarding "subjective perspective" of these two methods. Should we add `@brief` and `@details` to the `RobotHW::write()` and `RobotHW::read()` methods?

---

Another thought that came to my mind and as @matthew-reynolds [mentioned](https://github.com/ros-controls/ros_controllers/issues/462#issuecomment-595829508):

> these calculations don't perfectly fit into the model of the RobotHW read/update/write cycle anyways.

Maybe those tests of `DiffBot` weren't written with the `RobotHW` and its virtual methods in mind? If they were, I think we should use override for `DiffBot`'s `read` and `write` methods with the same method signatures as in `RobotHW`.

**Comment by bmagyar** [comment]
@fjp +1 for `@brief`

**Comment by fjp** [comment]
Ok, I'll try to improve the documentation for [`RobotHW::read`](https://github.com/ros-controls/ros_control/blob/b78bccb5f3768d1726db79acbe8837cc5187b515/hardware_interface/include/hardware_interface/robot_hw.h#L164) and [`RobotHW::write()`](https://github.com/ros-controls/ros_control/blob/b78bccb5f3768d1726db79acbe8837cc5187b515/hardware_interface/include/hardware_interface/robot_hw.h#L172) methods in another PR this week. 

But please bear with me, as I am new to ROS control and struggling a bit with the documentation as it is rather sparse and not all in one place... No offence though, I think ROS control is great and I just need to use it more in order to understand it better.

**Comment by bmagyar** [comment]
Anything you find worth mentioning please add here: https://github.com/ros-controls/roadmap/blob/master/documentation_resources.md in the form of a PR, we are trying to collect all docs on `ros_control` and unify them.

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
