### PR TITLE
Added check for ~/robot_description and fixed hardware interface abstraction bug

### PR DESCRIPTION
**Pull request by davetcoleman**
Small fixes I've found so far in the direction of https://github.com/ros-controls/ros_controllers/issues/43

### CODE REVIEW

**Comment by adolfo-rt** [comment]
Good catch about the vestigial PositionJointInterface occurrences!.

Could you describe the parameter namespace setup that requires reading the URDF from the root?. I thought that reading from the `root_nh` would be "good enough". The two main cases I had in mind being:
- Single robot scenarios: `root_nh` is the top-level namespace `/`, and both the controller_manager and the robot description hang from it.
- Multi-robot scenarios: `root_nh` is a robot-specific identifier `/foo_robot`, and both **this robot's** controller_manager and **this robot's** description hang from it.

I can accept the URDF patch, but before I'd like to understand the usecase(s) driving it.

**Comment by davetcoleman** [comment]
I'll admit I couldn't get the ideal fix to work for the namespace, I'm not sure what I was doing wrong, so I made this work around based on the [effort_controllers/joint_position_controller](https://github.com/ros-controls/ros_controllers/blob/hydro-devel/effort_controllers/src/joint_position_controller.cpp#L83).

Your original implementation did not look for `~/robot_description` but instead `~/namespace/robot_description`. I actually tried both the `searchParam` method to search backwards and I tried creating a `ros::NodeHandle root_nh("~")` but neither of those methods worked at first shot. Do you know what I did wrong?

But my fix now searches both `~/robot_description` but instead `~/namespace/robot_description`. Most MoveIt! robots have their robot_description loaded in the root.

**Comment by adolfo-rt** [comment]
> I'll admit I couldn't get the ideal fix to work for the namespace, I'm not sure what I was doing wrong, so I made this work around based on the effort_controllers/joint_position_controller.

These controllers are a legacy of the PR2 controller manager era, when multi-robot was not really a strong point. I would not necessarily use them as ground truth for these things.

> Your original implementation did not look for ~/robot_description but instead ~/namespace/robot_description. 

Not exactly.

The current implementation looks for the robot description in the controller manager's **root NodeHandle**, it does not make any other assumptions. This is whatever was supplied to the controller manager on [construction](https://github.com/ros-controls/ros_control/blob/hydro-devel/controller_manager/include/controller_manager/controller_manager.h#L78), and defaults to the root namespace `/`. gazebo_ros_control [sets](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/gazebo_ros_control_plugin.cpp#L141) it to `/namespace` (or `/` if no namespace is given).

> I actually tried both the searchParam method to search backwards and I tried creating a ros::NodeHandle root_nh("~") but neither of those methods worked at first shot. Do you know what I did wrong?

I can't really tell without knowing how you are namespacing things. Could you please post the namespace of your controller manager, and that of your robot description?. It would seem that you are pushing the controller manager to a namespace, while leaving the robot_description in the root. If this is the case, why so?.

> But my fix now searches both ~/robot_description but instead ~/namespace/robot_description. Most MoveIt! robots have their robot_description loaded in the root.

I'm guessing that most MoveIt robots work in single-robot deployments, which is by far the most common usecase, which makes perfect sense.

I would expect a multi-robot deployment to push all robot-specifics to a namespace, and this includes the robot description, the controller manager and its MoveIt! configuration, among other things. This can be done with a single `<group ns="namespace">` element when including your top-level robot launch file. In the absence of it, things would live in the root.

**Comment by davetcoleman** [comment]
I see your point of trying to keep the name spacing pure, and not allowing mixed environments to be used, but I suppose I'm trying to be more pragmatic with the current setup of how gazebo_ros_control and MoveIt! operates. 

> It would seem that you are pushing the controller manager to a namespace, while leaving the robot_description in the root. If this is the case, why so?.

MoveIt! currently does not really support name spacing afaik. Perhaps I should start this discussion since I'm trying to improve MoveIt and Gazebo support.

With Baxter, I'm forced to use namespacing in some areas because their SDK (which I cannot change) has everything namespaced with the ambiguous `/robot`.

I was also basing the dual-search feature on how Jonathan implemented it in [gazebo_ros_control](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/hydro-devel/gazebo_ros_control/src/gazebo_ros_control_plugin.cpp#L219).

In the bigger picture, I think we might want to engage ros-users with the issue that I think there are still plenty of places in ROS that use `~/robot_description` - but I may be mistaken.

> Could you please post the namespace of your controller manager, and that of your robot description?. 

 `/robot`

**Comment by davetcoleman** [comment]
I have the trajectory controller working pretty well in Gazebo! 

I also tried namespacing MoveIt's move_group but ran into lots of internal MoveIt issues (I don't know if this has been done before @isucan) so I gave up because I need to focus on other stuff.

**Comment by adolfo-rt** [comment]
The sign flip is now in the state error computation, and no longer in the PID call, as of 18694443807291093212a051e9e65b0010beb624. Things should be working as expected now.

**Comment by adolfo-rt** [comment]
> I have the trajectory controller working pretty well in Gazebo!

Great news!, we could schedule a release soon then. Do you have any other pending changes?.

> I also tried namespacing MoveIt's move_group but ran into lots of internal MoveIt issues (I don't know if this has been done before @isucan) so I gave up because I need to focus on other stuff.

I'd appreciate if you could share those errors at some point, maybe in moveit-users, because we're going to walk down this path in the near future.

**Comment by davetcoleman** [comment]
There is still the groovy pull request that I guess we can close. I feel like I should run it by Wim before we merge hydro into groovy though - so I'm waiting his email

I proposed a velocity_position_controller that is currently in a branch but I think I'll just move it to my account.

And I haven't implemented the VelocityJointInterface for the hardware interface adapter, but I think you know a lot more about what you are doing than I so if you wanted to... :)

**Comment by adolfo-rt** [comment]
> And I haven't implemented the VelocityJointInterface for the hardware interface adapter, but I think you know a lot more about what you are doing than I so if you wanted to... :)

I don't have neither the usecase nor the cycles ([YAGNI](http://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)). I'd be more than happy to help the next interested person in making this happen.

In the near future, I'm more interested in pushing the URDF transmission parser (which is done and tested, but needs Hydro validation), moving to Hydro once and for all, and integrating ros_control with MoveIt!.

**Comment by davetcoleman** [comment]
I've never heard of YAGNI until now but I totally agree!

I can again help with Hydro validation and MoveIt questions

**Pull request merged**
