### PR TITLE
Rebased #83: Add JointTrajectoryController specification for SplineJointInterface.

### PR DESCRIPTION
**Pull request by mathias-luedtke**
Rebased #83 to indigo-devel
Merged version compiles, unit tests finished successfully, not tested any further

### CODE REVIEW

**Comment by adolfo-rt** [comment]
Great news!. If you're going to be a user of this new hardware interface adapter, I prefer to wait until correct behavior has been experimentally validated. I'll give the merge a go then.

This is because only the position hardware interface has test coverage, all other adapters, including this one, have none.

**Comment by mathias-luedtke** [comment]
I am not going to use it, because we don't have any hardware that supports pos_vel_acc.
We will use the pos_vel interface, but with a custom controller (no trajectories).

**Comment by adolfo-rt** [comment]
@igorec, any chance you can give this one a test drive? now that @ipa-mdl has ported the feature to the current development branch.

**Comment by mathias-luedtke** [comment]
rebased on current `indigo-devel` branch, let's see if travis is happy

**Comment by bmagyar** [comment]
Would you like some fries...ehm tests with this? :)
Even a simplistic one, just to exercise basic behaviour.

**Comment by mathias-luedtke** [comment]
I cannot test it, I still don't have a matching hardware interface for it.
@anderwm might have one :)

**Comment by anderwm** [comment]
I may be able to test this, I have some more reading to do first to make sure I understand everything as well as I think I do. I wrote a multi joint controller for the dynamixel stack that takes POS, vel on multiple joints. If this helps anybody else test this let me know.

**Comment by mathias-luedtke** [comment]
> I wrote a multi joint controller for the dynamixel stack that takes POS, vel on multiple joints. If this helps anybody else test this let me know.

This PR adds support in a controller as well. What we need for a test is a corresponding hardware interface..

**Comment by anderwm** [comment]
I tested the posvelacc::JointTrajectoryController but only used pos and vel in my hardware interface. It worked as expected, see #254 for details.

**Comment by graiola** [comment]
@bmagyar do we proceed with the merge on indigo?

**Comment by bmagyar** [comment]
I do support merging this, however it is late now to add new features to Indigo. Give me a Kinetic-rebase and we can merge that.

**Comment by mathias-luedtke** [comment]
>  Give me a Kinetic-rebase and we can merge that.

Too late ;)
https://github.com/ros-controls/ros_controllers/pull/296

It's fine for me to have it only in kinetic.
We should merge this PR only if it is requested by some users.

**Comment by bmagyar** [comment]
Oh, thanks! I don't have a great long-term memory :D 

I'll close this one for now as we shouldn't really be adding any new stuff to Indigo anymore. If there is a strong demand we can talk about it.

**Pull request closed without merging**
