### PR TITLE
Use #pragma once

### PR DESCRIPTION
**Pull request by matthew-reynolds**
Part of ros-controls/ros_control#403. Corresponds to ros-controls/ros_control#406.

Replace all preprocessor header guards with `#pragma once`. Also adds missing header guard to a few files, including some tests. Every `.h` file now includes `#pragma once`.

(Note: my editor stripped all trailing whitespace in the files I touched. This is particularly apparent in `gripper_action_controller`. Although this change is unrelated to this PR, it doesn't really warrant its own PR, so I left it here since it ought to be dealt with at some point)

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
`#pragma once` is not defined in the standard.
It is supported by most modern compilers, but might not work properly in all cases.
I am note sure, if all compilers for embedded systems support it.

I would rather keep the include guards (and add the missing ones).

One option would be to include both, `#pragma once` and include guards, but I don't think that it is worth the effort.

**Comment by matthew-reynolds** [comment]
>One option would be to include both, #pragma once and include guards, but I don't think that it is worth the effort.

I agree, I don't see much benefit to using both. AFAIK most compilers (at least GCC and clang, I believe) optimize them in a similar way to `#pragma once` anyways. If we want the #ifndef guards, I think we should just remove `#pragma once`.

>I would rather keep the include guards

This is fine by me, but it sounds like this is a difference of opinion between you and @bmagyar. I will wait until you two (and perhaps other maintainers) reach a consensus.

> and add the missing ones

:+1: If we decide against this PR, I will certainly open up another to add those missing guards.

**Comment by bmagyar** [comment]
@ipa-mdl let's find some common ground here. 
I've got this ref: https://en.wikipedia.org/wiki/Pragma_once#Portability
Which particular embedded compiler are we talking about? Most standard ones use GCC by now as far as I know.

**Comment by mathias-luedtke** [comment]
> Which particular embedded compiler are we talking about?

None in particular. This was more of an open question.

> I've got this ref: https://en.wikipedia.org/wiki/Pragma_once#Portability

This only states some level of support. But since there is no standards, the semantics vary.
TBH I don't see the point in replacing the  working include guards for now.

**Comment by matthew-reynolds** [comment]
Let's loop back on this:

`ros_control` has been using `#pragma once` since Jan 3 (ros-controls/ros_control#406). From scrolling through Discourse and ROS Answers, I haven't seen any backlash on this, but of course lots of big companies maintain their own forks, and we know that the vast majority of users wouldn't encounter issues anyways since compiler support is so broad.

But there is of course the important question of what benefit this really brings us, and whether that benefit outweighs any downsides to losing standard-compliance.

Where do we go from here? My only real preference is consistency between our repos, so either this should be merged or ros-controls/ros_control#406 should be reverted.

**Comment by bmagyar** [comment]
Let's go ahead with merging, we can revert both if there's complaints.
Could you please fix the conflict?

**Comment by matthew-reynolds** [comment]
Rebased on latest `melodic-devel`

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
