### PR TITLE
Controller for differential drive wheel base

### PR DESCRIPTION
**Pull request by po1**
### Diff-drive controller

This controller leverages `ros_control` and furnishes a mean to control a differential drive wheel base.
It has been implemented and tested on the REEM robot.

Overview of its features:
- takes a `sensor_msgs/Twist` message as an input, and will control the wheel base assuming a set of two coaxial wheels through two `VelocityJointInterface`.
- publishes odometry through an `nav_msgs/Odometry` and to `tf`, with a transform from `/odom` to `/base_link`
- implements task-space velocity and acceleration limits
- automatic stop after command timeout

The configuration is done through `rosparam`, here is an example of a controller parameter file:

``` yaml
mobile_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'wheel_left_joint'
  right_wheel : 'wheel_right_joint'
  publish_rate: 50.0 # defaults to 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.25

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0 # m/s
      min_velocity           : -0.5 #m/s
      has_acceleration_limits: true
      max_acceleration       : 0.8 # m/s^2
      min_acceleration       : -0.4 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.7 # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.5 # rad/s^2
```

Request for review:
@adolfo-rt @bmagyar @efernandez

### CODE REVIEW

**Comment by adolfo-rt** [comment]
First and foremost, good stuff!.

Here go some comments. They don't target the algorithm, as you know more about it than I do, and I've seen it working countless times by now.
- The assumptions the controller makes on the URDF model are not documented anywhere (frame orientations and layout, the fact that wheels need a cylinder collision geometry). This is a must for new users. There should be sufficient developper doc in the Doxy tags, and a user-oriented doc in the ROS wiki page, which I guess is in the works, right? ;-).
- There does not seem to be a test case exercising a controller that fails to load, e.g., joints specified in the yaml file not existing in the URDF, and a URDF not complying with the controller's assumptions.
- The [diffbot model](https://github.com/pal-robotics/ros_controllers/blob/diff-drive-controller/diff_drive_controller/test/diffbot.xacro) uses eight spaces per indentation level, a bit too much. Two should be more than enough.
- The integration methods [here](https://github.com/pal-robotics/ros_controllers/blob/diff-drive-controller/diff_drive_controller/include/diff_drive_controller/odometry.h#L136) could use method names reflecting more the action taken, e.g., `integrationExact` -> `integrateExact`. This is part of the private API, so no big deal, but it's good practice that method calls are named by what the do (in this case, they _integrate_).
- [integrationByRungeKutta(...)](https://github.com/pal-robotics/ros_controllers/blob/diff-drive-controller/diff_drive_controller/include/diff_drive_controller/odometry.h#L147) implements a second order method (and the Doxy clearly states it, so good). Still, could we reflect it in the method name as well?. When I first saw the call in the source file, I though it was referring to _the_ Runge Kutta method ([classical, or RK4](http://en.wikipedia.org/wiki/List_of_Runge%E2%80%93Kutta_methods#Classic_fourth-order_method)). Maybe `integrateRungeKutta2(...)`, which is shorter yet more explicit (and does not create false expectations :-).
- Most of ros_control and ros_controllers use backslash, and not ampersand for Doxygen tags. This is the recommended convention, e.g., `\brief` instead of `@brief`.

**Comment by po1** [comment]
@adolfo-rt thanks for the input!
As you have seen on our side, all has been taken into account, discussed and implemented (and discussed again).

**Comment by adolfo-rt** [comment]
@bmagyar, @efernandez, @po1, this is a great addition to ros_controllers!. A diff-drive controller lowers the entry barrier to ros_control for quite a few platforms. Your efforts are much appreciated.

Now, to celebrate, let's populate this page ;-) http://wiki.ros.org/diff_drive_controller

I'm merging, as the Travis CI is passing, and we've received no additional developer feedback.

**Comment by davetcoleman** [comment]
I just caught up on github emails, but great effort in testing and documentation!

**Pull request merged**
