### PR TITLE
diff drive skid steer

### PR DESCRIPTION
**Pull request by bmagyar**
This PR is an update from the hydro-devel branch of ros_controllers from PAL Robotics, and it depends on https://github.com/ros-controls/ros_controllers/pull/137. 

It adds support for multiple wheels per side to the diff_drive_controller.

This version of the diff_drive_controller is the one that is currently running on all PAL Robotics platforms and on the Jackal from Clearpath Robotics.

Related PRs:
https://github.com/pal-robotics/ros_controllers/pull/42
https://github.com/ros-controls/ros_controllers/issues/10

### CODE REVIEW

**Comment by bmagyar** [comment]
@mikepurvis, @adolfo-rt

**Comment by adolfo-rt** [comment]
A visual inspection of the code looks OK. There are unit tests (horray!) and the controller has been validated in different hardware platforms, so from my part:

+1

It's great to see that writing a new controller was not necessary in the end. Good stuff guys!

**Comment by bmagyar** [comment]
I'll fix this build tonight.

**Comment by mikepurvis** [comment]
Looks great, thanks very much for the work on this.

As [noted in the sig mailing list](#!topic/ros-sig-robot-control/-moCZEkHJZY), I am having a weird issue with my system using this controller. However, I suspect it's a problem with my hardware node, or elsewhere in my system, rather than with the controller specifically.

+1 from me.

**Comment by bmagyar** [comment]
Test xacros fixed.

**Pull request merged**
