### PR TITLE
Exposed the joint trajectory controller verbose setting as a parameter.

### PR DESCRIPTION
**Pull request by bponsler**
Expose the joint trajectory controller verbose setting as a parameter

### CODE REVIEW

**Comment by bmagyar** [comment]
This is something I think should be documented well. The verbose parameter there is for advanced use as it breaks real-time safety by using ROS logging services. I would not "open it to the public" as a parameter. In it's current state there has to be a strong need to go debugging the controller and the one seeking it will find it. 

What do you think? 

What do you think, gentlemen? @graiola @ipa-mdl

**Comment by bponsler** [comment]
That seems reasonable, totally fine if you want to pass on this.

**Comment by bmagyar** [comment]
Maybe you could still change this PR so that instead of opening it as a param, you add a comment in the code to explain that the verbose flag possibly breaks realtime-safety.

**Comment by bponsler** [comment]
I'm fine with adding a comment, but I would suggest also displaying a runtime warning to the user whenever the verbose flag is enabled to help prevent someone from accidentally leaving the flag enabled.

Thoughts?

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
There is a failing test on travis due a timeout but this code it only affecting a print. Merging...

**Pull request merged**
