### PR TITLE
Switch CI to GitHub actions

### LINKED ISSUE #539: Use GitHub Actions over Travis
With travis-ci.org finally being shut down this month in favor of travis-ci.com, lots of jobs are taking a long time to queue ([See this support thread](https://travis-ci.community/t/builds-hang-in-queued-state/10250)) and we'll have to migrate by the end of the month anyways.

We should either migrate all the ros1 repos to travis-ci.com ([Instructions here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository)) or, more likely, switch to GitHub Actions like the ros2 repos use. Should be a pretty minor change either way given industrial_ci's support for both.

@bmagyar Not sure if this is something I can help with since these CI things are more in the hands of the repo owners, but let me know if I can help in any way.

### PR DESCRIPTION
**Pull request by matthew-reynolds**
Closes #539, and also adds code coverage.

Still working through a few quirks, in particular with the coverage, so only draft PR for now.

### CODE REVIEW

**Comment by matthew-reynolds** [comment]
@bmagyar Can you check if GH Actions are enabled for this repo in https://github.com/ros-controls/ros_controllers/settings/actions? Not sure why they're not triggering here, it shouldn't matter whether it's a draft or full PR.

**Comment by matthew-reynolds** [comment]
~Waiting on https://github.com/colcon/colcon-lcov-result/pull/22 so I can remove my manual `lcov` stuff and mark this PR as ready~

colcon-lcov-result v0.5.0 is released, but will take a few days to get into the package repos. Will check back in a few days.

**Comment by matthew-reynolds** [comment]
In the interest of getting this merged before the end of the year when travis-ci.org goes dark, I'll split out the codecov to a follow-up PR. If this gets the green light I'll mirror the changes over to the other ROS1 repos.

Second follow-up will be updating the badges in the READMEs.

@bmagyar Can you check that GH actions are enabled for the repo?

**Comment by bmagyar** [comment]
They are enabled, I'm wondering if it needs to be on master first to work? Let's try

**Comment by matthew-reynolds** [comment]
Odd, looks like they ran after being merged. On my test PR within my fork, they ran fine in the PR, I wonder what's different about this PR. Anyways, thanks for merging, I will work on those followups :)

**Comment by bmagyar** [comment]
I think it just had to be "warm startd" by having a gh config in the first place

**Pull request merged**
