### PR TITLE
dont print warning about dropped first point

### LINKED ISSUE #291: joint_trajectory_controller - Always dropping first trajectory point
If a trajectory has no specified start time (0) and time_from_start of the first point is zero the first point will always be dropped. 

Changing
https://github.com/ros-controls/ros_controllers/blob/3ee947a8a51f0a7594e54b2a79b95bc01d1591dc/joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_msg_utils.h#L57
< to <= stops this behaviour.

Not sure if this would be the best fix.

Any comments?

### PR DESCRIPTION
**Pull request by jschleicher**
Same as #366 for melodic. I've only tested this on kinetic; please consider to double-check it.

Closes #291

### CODE REVIEW

**Review by bmagyar — APPROVED** [review]
LGTM

**Comment by bmagyar** [comment]
@graiola please merge if approve

**Review by mathias-luedtke — DISMISSED** [review]
Please do not merge before https://github.com/ros-controls/ros_controllers/pull/366

**Comment by graiola** [comment]
It seems that the ci went in timeout. I am restarting it.

**Pull request merged**
