### PR TITLE
Catkin

### PR DESCRIPTION
**Pull request by jbohren**
Not ready to merge yet, but might as well post it here so people don't duplicate work.

### CODE REVIEW

**Comment by davetcoleman** [comment]
Thanks for putting this notice here, looking forward to this being merged in.

**Comment by jbohren** [comment]
This now has a hybrid buildsystem, so it can be built in catkin and rosbuild workspaces. The only things missing are cmake install commands so it can be released with bloom.

**Comment by davetcoleman** [comment]
> The only things missing are cmake install commands so it can be released with bloom.

Did you just not bother adding this, or is this a limitation of a hybrid build system?

**Comment by davetcoleman** [comment]
Also, are `mainpage.dox` files required in rosbuild? It seems they were never really used, and they are removed with catkin. It would be nice to delete them to cleanup the root directories of all the "cruft".

**Comment by jbohren** [comment]
No, I just hadn't done it yet, but I added the install targets in a
subsequent PR.

**Pull request merged**
