### PR TITLE
Fix test for ackermann_steering_controller

### LINKED ISSUE #460: Sporadic failure of ackermann_steering_controller test
Failing test:
`ackermann_steering_controller_default_odom_frame_test`

Log:
```
[ RUN      ] AckermannSteeringControllerTest.testOdomTopic
/home/imartini/catkin_ws/src/ros_controllers/ackermann_steering_controller/test/ackermann_steering_controller_default_odom_frame_test/ackermann_steering_controller_default_odom_frame_test.cpp:60: Failure
      Expected: odom_msg.header.frame_id.c_str()
      Which is: ""
To be equal to: "odom"
[  FAILED  ] AckermannSteeringControllerTest.testOdomTopic (212 ms)
```

### PR DESCRIPTION
**Pull request by martiniil**
Wait until controller is running and msg was received. Fixes #460.

Other tests are failing as well. Should I continue on this branch or keep the PRs small?
@bmagyar what do you prefer?

### CODE REVIEW

**Comment by bmagyar** [comment]
I think this may have put the rest of the tests out of their fragile timing setup for this controller. 
If you could keep these fixes focusing on one controller at a time that'd be great.

**Comment by martiniil** [comment]
@bmagyar ready for review

This doesn't change that some tests are still quite fragile. But it improves a lot. I merged with #457 on my local machine and got no failures most of the time.

**Review by bmagyar — APPROVED** [review]
Thanks very much for this, you've probably saved some trees (I've clicked Travis' retry buttons so many times...)

**Comment by jordan-palacios** [comment]
LGTM! :+1:

**Pull request merged**
