### PR TITLE
Mallan/kinetic allow sphere wheels in diff drive

### PR DESCRIPTION
**Pull request by mallanmba**
repeat of pull request #250 on kinetic-devel

### CODE REVIEW

**Comment by graiola** [comment]
Hello,

Thank you for sharing your code with us.
After checking your pr I noticed that in the .test files you use xacro.py instead of xacro but the former is deprecated. Could you change it?
Also, could you rename the test files related to the cylinder wheels to have consistent naming?

Thanks

**Comment by bmagyar** [comment]
Bump. @mallanmba we could get this in to the next Kinetic and Lunar release. Those changes won't take you a lot of time to implement ;)

**Comment by mallanmba** [comment]
Sorry! Dropped the ball on this. I'm happy to make the change for xacro.py,
but I'm unclear about the consistent naming - what are you looking for?
Thanks,
-Mark

**Comment by graiola** [comment]
Hello!

The idea would be to change some files name inside the test folder:

- diffbot.xacro -> diffbot_cylinder_wheels.xacro

- wheel.xacro -> cylinder_wheel.xacro

Moreover, I think it would be nice to have a symmetric test for cylinder as for diff_drive_radius_sphere.test 

Note:
in diff_drive_radius_sphere.test the test-name should be different from the one in diff_drive_radius_param.test

@bmagyar , do you have any other advice?

**Comment by bmagyar** [comment]
I'm not sure that `diff_drive_radius_sphere.test` should have different tests as it it practically running the same test on a different configuration.

**Comment by tfoote** [comment]
Closing this as #278 included and extended the work of @mallanmba in this PR and has been merged.

**Comment by bmagyar** [comment]
Thanks!

**Pull request closed without merging**
